name: running_society
version: 1.0.0+1

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  english_words: ^4.0.0-nullsafety.0
  flutter_lorem: ^2.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  supabase: ^0.0.1-dev.10
  google_fonts: ^2.0.0
  convex_bottom_bar: ^3.0.0
  font_awesome_flutter: ^9.0.0
  table_calendar: ^3.0.0-nullsafety.1
  agora_rtc_engine: ^4.0.0-rc.3
  permission_handler: ^6.1.1
  gotrue: ^0.0.1-dev.9
  shared_preferences: ^2.0.5
  rounded_loading_button: ^1.0.18
  url_launcher: ^6.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0

flutter:
  uses-material-design: true
  assets: 
    - assets/coaches_images/
    - assets/img/
